2024-05-11 23:40:17.839 -05:00 [ERR] Connection id "0HN3I7I0TQL1Q", Request id "0HN3I7I0TQL1Q:00000002": An unhandled exception was thrown by the application.
System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Release.Helper.Proxy.ProxyHttpClient.InvokeWebApi[T](HttpMethod verb, String url, String jsonData, String defaultMediaType, String authorizationToken, String authorizationMethod, Int32 timeout)
   at Release.Helper.Proxy.BaseProxy.InvokeWebApi[T](HttpMethod verb, String urlAction, String parameters, Int32 timeout)
   at Prod.GESTORPLUS.Presentacion.Configuracion.Proxys.ComunConsultaProxy.GetConceptosList() in C:\gestorplus\Prod.GESTORPLUS.Presentacion.Configuracion\Proxys\ComunConsultaProxy.cs:line 36
   at Prod.GESTORPLUS.Presentacion.MVC.Controllers.ComunController.GetConceptos() in C:\gestorplus\Prod.GESTORPLUS.Presentacion.MVC\Controllers\ComunController.cs:line 55
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.ProcessRequestsAsync()
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

2024-05-11 23:40:17.839 -05:00 [ERR] Connection id "0HN3I7I0TQL1N", Request id "0HN3I7I0TQL1N:00000007": An unhandled exception was thrown by the application.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Release.Helper.Proxy.ProxyHttpClient.InvokeWebApi[T](HttpMethod verb, String url, String jsonData, String defaultMediaType, String authorizationToken, String authorizationMethod, Int32 timeout)
   at Release.Helper.Proxy.BaseProxy.InvokeWebApi[T](HttpMethod verb, String urlAction, String parameters, Int32 timeout)
   at Prod.GESTORPLUS.Presentacion.Configuracion.Proxys.ComunConsultaProxy.GetTipoPagoList() in C:\gestorplus\Prod.GESTORPLUS.Presentacion.Configuracion\Proxys\ComunConsultaProxy.cs:line 53
   at Prod.GESTORPLUS.Presentacion.MVC.Controllers.ComunController.GetTipoPago() in C:\gestorplus\Prod.GESTORPLUS.Presentacion.MVC\Controllers\ComunController.cs:line 93
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.ProcessRequestsAsync()
2024-05-11 23:41:01.231 -05:00 [ERR] Connection id "0HN3I7I0TQL1P", Request id "0HN3I7I0TQL1P:00000004": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Sucedió un inconveniente al procesar su solicitud, por favor vuelva a intentar en unos minutos
   at Release.Helper.Proxy.ProxyHttpClient.InvokeWebApi[T](HttpMethod verb, String url, String jsonData, String defaultMediaType, String authorizationToken, String authorizationMethod, Int32 timeout)
   at Release.Helper.Proxy.BaseProxy.InvokeWebApi[T](HttpMethod verb, String urlAction, String parameters, Int32 timeout)
   at Prod.GESTORPLUS.Presentacion.Configuracion.Proxys.ComprobanteConsultaProxy.GetArchivoAdjunto(ArchivoAdjuntoFilter filtro) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.Configuracion\Proxys\ComprobanteConsultaProxy.cs:line 44
   at Prod.GESTORPLUS.Presentacion.MVC.Controllers.ComprobanteController.GetArchivoAdjunto(ArchivoAdjuntoFilter request) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.MVC\Controllers\ComprobanteController.cs:line 95
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.ProcessRequestsAsync()
2024-05-11 23:41:01.251 -05:00 [ERR] Connection id "0HN3I7I0TQL1O", Request id "0HN3I7I0TQL1O:0000000C": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Sucedió un inconveniente al procesar su solicitud, por favor vuelva a intentar en unos minutos
   at Release.Helper.Proxy.ProxyHttpClient.InvokeWebApi[T](HttpMethod verb, String url, String jsonData, String defaultMediaType, String authorizationToken, String authorizationMethod, Int32 timeout)
   at Release.Helper.Proxy.BaseProxy.InvokeWebApi[T](HttpMethod verb, String urlAction, String parameters, Int32 timeout)
   at Prod.GESTORPLUS.Presentacion.Configuracion.Proxys.ComprobanteConsultaProxy.GetComprobantes(ComprobanteFilter filtro) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.Configuracion\Proxys\ComprobanteConsultaProxy.cs:line 20
   at Prod.GESTORPLUS.Presentacion.MVC.Controllers.ComprobanteController.GetComprobantes(ComprobanteFilter request) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.MVC\Controllers\ComprobanteController.cs:line 50
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.ProcessRequestsAsync()
2024-05-11 23:41:01.266 -05:00 [ERR] Connection id "0HN3I7I0TQL1S", Request id "0HN3I7I0TQL1S:00000006": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Sucedió un inconveniente al procesar su solicitud, por favor vuelva a intentar en unos minutos
   at Release.Helper.Proxy.ProxyHttpClient.InvokeWebApi[T](HttpMethod verb, String url, String jsonData, String defaultMediaType, String authorizationToken, String authorizationMethod, Int32 timeout)
   at Release.Helper.Proxy.BaseProxy.InvokeWebApi[T](HttpMethod verb, String urlAction, String parameters, Int32 timeout)
   at Prod.GESTORPLUS.Presentacion.Configuracion.Proxys.ComprobanteConsultaProxy.GetDetalleComprobantes(DetalleComprobanteFilter filtro) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.Configuracion\Proxys\ComprobanteConsultaProxy.cs:line 36
   at Prod.GESTORPLUS.Presentacion.MVC.Controllers.ComprobanteController.GetDetalleComprobantes(DetalleComprobanteFilter request) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.MVC\Controllers\ComprobanteController.cs:line 79
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.ProcessRequestsAsync()
2024-05-11 23:41:01.273 -05:00 [ERR] Connection id "0HN3I7I0TQL1R", Request id "0HN3I7I0TQL1R:00000006": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Sucedió un inconveniente al procesar su solicitud, por favor vuelva a intentar en unos minutos
   at Release.Helper.Proxy.ProxyHttpClient.InvokeWebApi[T](HttpMethod verb, String url, String jsonData, String defaultMediaType, String authorizationToken, String authorizationMethod, Int32 timeout)
   at Release.Helper.Proxy.BaseProxy.InvokeWebApi[T](HttpMethod verb, String urlAction, String parameters, Int32 timeout)
   at Prod.GESTORPLUS.Presentacion.Configuracion.Proxys.ComprobanteConsultaProxy.GetFlujoComprobantes(FlujoComprobanteFilter filtro) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.Configuracion\Proxys\ComprobanteConsultaProxy.cs:line 40
   at Prod.GESTORPLUS.Presentacion.MVC.Controllers.ComprobanteController.GetFlujoComprobantes(FlujoComprobanteFilter request) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.MVC\Controllers\ComprobanteController.cs:line 87
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.ProcessRequestsAsync()
2024-05-11 23:44:25.858 -05:00 [ERR] Connection id "0HN3I7I0TQL1T", Request id "0HN3I7I0TQL1T:00000006": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Sucedió un inconveniente al procesar su solicitud, por favor vuelva a intentar en unos minutos
   at Release.Helper.Proxy.ProxyHttpClient.InvokeWebApi[T](HttpMethod verb, String url, String jsonData, String defaultMediaType, String authorizationToken, String authorizationMethod, Int32 timeout)
   at Release.Helper.Proxy.BaseProxy.InvokeWebApi[T](HttpMethod verb, String urlAction, String parameters, Int32 timeout)
   at Prod.GESTORPLUS.Presentacion.Configuracion.Proxys.RegisterComandoProxy.Registrar(Register register) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.Configuracion\Proxys\RegisterComandoProxy.cs:line 20
   at Prod.GESTORPLUS.Presentacion.MVC.Controllers.RegisterController.Registrar(Register request) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.MVC\Controllers\RegisterController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.ProcessRequestsAsync()
